function f = QuadrotorStateFcn(in1,in2)
%QuadrotorStateFcn
%    F = QuadrotorStateFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    25-Apr-2024 12:37:07

n1 = in2(8,:);
n2 = in2(9,:);
n3 = in2(10,:);
phi_t = in1(4,:);
phi_dot_t = in1(10,:);
psi_t = in1(6,:);
psi_dot_t = in1(12,:);
r1 = in2(5,:);
r2 = in2(6,:);
r3 = in2(7,:);
theta_t = in1(5,:);
theta_dot_t = in1(11,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
x_dot_t = in1(7,:);
y_dot_t = in1(8,:);
z_dot_t = in1(9,:);
t2 = cos(phi_t);
t3 = cos(psi_t);
t4 = cos(theta_t);
t5 = sin(phi_t);
t6 = sin(psi_t);
t7 = sin(theta_t);
t8 = phi_t.*2.0;
t9 = psi_dot_t.^2;
t15 = u1+u2+u3+u4;
t10 = t2.^2;
t11 = t4.^2;
t12 = sin(t8);
t13 = t3.*t5;
t14 = t5.*t6;
t17 = t2.*t3.*t7;
t18 = t2.*t6.*t7;
t16 = 1.0./t11;
t19 = -t18;
t20 = t14+t17;
t21 = t13+t19;
et1 = t16.*(n1.*2.0e+2+u2.*4.0e+1-u4.*4.0e+1+n3.*t7.*2.0e+2-n1.*t10.*1.0e+2+t7.*u1.*2.0-t7.*u2.*2.0+t7.*u3.*2.0-t7.*u4.*2.0-t10.*u2.*2.0e+1+t10.*u4.*2.0e+1-n3.*t7.*t10.*1.0e+2+n1.*t10.*t11.*1.0e+2+psi_dot_t.*t4.*theta_dot_t.*4.96e+2-t7.*t10.*u1+t7.*t10.*u2-t7.*t10.*u3+t7.*t10.*u4+t10.*t11.*u2.*2.0e+1-t10.*t11.*u4.*2.0e+1-psi_dot_t.*t4.*t10.*theta_dot_t.*2.48e+2-t2.*t5.*t9.*t11.*2.48e+2-psi_dot_t.*t4.^3.*t10.*theta_dot_t.*2.48e+2+t2.*t5.*t11.*theta_dot_t.^2.*2.48e+2+n2.*t2.*t4.*t5.*t7.*1.0e+2+phi_dot_t.*t4.*t7.*t10.*theta_dot_t.*2.48e+2-t2.*t4.*t5.*t7.*u1.*2.0e+1+t2.*t4.*t5.*t7.*u3.*2.0e+1+phi_dot_t.*psi_dot_t.*t2.*t5.*t7.*t11.*2.48e+2);
et2 = 1.0./2.48e+2;
mt1 = [x_dot_t;y_dot_t;z_dot_t;phi_dot_t;theta_dot_t;psi_dot_t;r3.*t20.*2.0+t15.*t20.*2.0-r2.*(t2.*t6-t7.*t13).*2.0+r1.*t3.*t4.*2.0;r3.*t21.*-2.0-t15.*t21.*2.0+r2.*(t2.*t3+t7.*t14).*2.0+r1.*t4.*t6.*2.0;r1.*t7.*-2.0+r3.*t2.*t4.*2.0+r2.*t4.*t5.*2.0+t2.*t4.*t15.*2.0-9.81e+2./1.0e+2;et1.*et2];
mt2 = [(n2.*t4.*2.0e+2+n3.*t12.*1.0e+2-t4.*u1.*4.0e+1+t4.*u3.*4.0e+1+t12.*u1-t12.*u2+t12.*u3-t12.*u4-phi_dot_t.*psi_dot_t.*t11.*4.96e+2+n2.*t4.*t10.*2.0e+2-t4.*t10.*u1.*4.0e+1+t4.*t10.*u3.*4.0e+1+phi_dot_t.*psi_dot_t.*t10.*t11.*4.96e+2+n1.*t2.*t5.*t7.*2.0e+2-t7.*t9.*t10.*t11.*4.96e+2+t2.*t5.*t7.*u2.*4.0e+1-t2.*t5.*t7.*u4.*4.0e+1-phi_dot_t.*t2.*t4.*t5.*theta_dot_t.*4.96e+2+psi_dot_t.*t2.*t4.*t5.*t7.*theta_dot_t.*4.96e+2)./(t4.*4.96e+2)];
mt3 = [(t16.*(n3.*2.0e+2+u1.*2.0-u2.*2.0+u3.*2.0-u4.*2.0+n1.*t7.*2.0e+2-n3.*t10.*1.0e+2+t7.*u2.*4.0e+1-t7.*u4.*4.0e+1-t10.*u1+t10.*u2-t10.*u3+t10.*u4+psi_dot_t.*theta_dot_t.*sin(theta_t.*2.0).*2.48e+2-n1.*t7.*t10.*1.0e+2-t7.*t10.*u2.*2.0e+1+t7.*t10.*u4.*2.0e+1+n2.*t2.*t4.*t5.*1.0e+2+phi_dot_t.*t4.*t10.*theta_dot_t.*2.48e+2-t2.*t4.*t5.*u1.*2.0e+1+t2.*t4.*t5.*u3.*2.0e+1+phi_dot_t.*psi_dot_t.*t2.*t5.*t11.*2.48e+2-psi_dot_t.*t4.*t7.*t10.*theta_dot_t.*2.48e+2-t2.*t5.*t7.*t9.*t11.*2.48e+2))./2.48e+2];
f = [mt1;mt2;mt3];
